[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QML = "2db162a6-7e43-52c3-8d84-290c1c42d82a"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
