# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      env:
        - QML_SKIP_GUI_TESTS=1
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
            - qtdeclarative5-dev
            - qtdeclarative5-qtquick2-plugin
            - qtdeclarative5-dialogs-plugin
            - qtdeclarative5-controls-plugin
            - qtdeclarative5-quicklayouts-plugin
            - qtdeclarative5-window-plugin
            - qmlscene
            - qt5-default
      julia: release
    - os: osx
      compiler: "clang"
      julia: nightly
notifications:
  email: true
