name = "QML"
uuid = "2db162a6-7e43-52c3-8d84-290c1c42d82a"
authors = ["Bart Janssens <bart@bartjanssens.org>"]
version = "0.7.1"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Mesa_jll = "78dcde23-ec64-5e07-a917-6fe22bbc0f45"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
jlqml_jll = "6b5019fb-a83d-5b4e-a9f7-678a36c28df7"

[compat]
ColorTypes = "0.11"
CxxWrap = "0.12"
MacroTools = "0.5"
Observables = "0.5"
Requires = "1.0"
jlqml_jll = "0.4"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "LibGit2", "Plots", "Test", "BenchmarkTools"]
