name = "QML"
uuid = "2db162a6-7e43-52c3-8d84-290c1c42d82a"
authors = ["Bart Janssens <bart@bartjanssens.org>"]
version = "0.5.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
