name = "QML"
uuid = "2db162a6-7e43-52c3-8d84-290c1c42d82a"
authors = ["Bart Janssens <bart@bartjanssens.org>"]
version = "0.8.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Qt6Wayland_jll = "e99dba38-086e-5de3-a5b1-6e4c66e897c3"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
jlqml_jll = "6b5019fb-a83d-5b4e-a9f7-678a36c28df7"

[compat]
ColorTypes = "0.11"
CxxWrap = "0.14.0"
MacroTools = "0.5"
Observables = "0.5"
Requires = "1.0"
jlqml_jll = "0.5.3"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Qt65Compat_jll = "f5784262-74e5-52be-b835-f3e8a3cf8710"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "LibGit2", "Colors", "Test", "BenchmarkTools", "Qt65Compat_jll"]
